Revert "Address FreeBSD bug 281612"
This reverts commit ba9d5654bd02fbc56f002b1fb9104f8cb15262fb.

.../unoxml/source/xpath/xpathapi.cxx:386:27: error: assigning to 'xmlStructuredErrorFunc' (aka 'void (*)(void *, const _xmlError *)') from incompatible type 'void (void *, const xmlErrorPtr)' (aka 'void (void *, _xmlError *const)'): type mismatch at 2nd parameter ('const xmlError *' (aka 'const _xmlError *') vs 'const xmlErrorPtr' (aka '_xmlError *const'))
  386 |         xpathCtx->error = structured_error_func;
      |                           ^~~~~~~~~~~~~~~~~~~~~
1 error generated.